# Generated by Django 4.2.3 on 2023-07-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_alter_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
